---

- name: RabbitMQ | Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started

- name: RabbitMQ | Ensure the users is removed
  rabbitmq_user: user={{item}} state=absent
  with_items: rabbitmq_user_remove

- name: RabbitMQ | Ensure the users is present
  rabbitmq_user: >
      user={{item.user}}
      password={{item.password}}
      configure_priv={{item.configure_priv|default('.*')}}
      read_priv={{item.read_priv|default('.*')}}
      write_priv={{item.write_priv|default('.*')}}
      vhost={{item.vhost|default('/')}}
      tags={{item.tags|default('')}}
  with_items: rabbitmq_users