---
- name: RabbitMQ | Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started

- name: RabbitMQ | Ensure the vhosts is present
  rabbitmq_vhost: name={{item}}
  with_items: rabbitmq_vhosts